databases:
  - name: postgres
    # databaseName: mysite
    # user: mysite
    ipAllowList: []

services:
  - type: web
    name: rails
    env: ruby
    buildCommand: "./bin/render-build.sh"
    # startCommand: "bundle exec puma -C config/puma.rb"
    startCommand: "./bin/dev"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false